export const ANALYTICS_EVENTS = {
  // App lifecycle
  APP_OPEN: 'APP_OPEN',
  PAGE_VIEW: 'PAGE_VIEW',
  SESSION_STARTED: 'SESSION_STARTED',
  SESSION_ENDED: 'SESSION_ENDED',
  API_SUCCESS: 'API_SUCCESS',
  API_FAILURE: 'API_FAILURE',
  UNHANDLED_ERROR: 'UNHANDLED_ERROR',

  // Auth
  LOGIN_PAGE_VIEWED: 'LOGIN_PAGE_VIEWED',
  OTP_SENT: 'OTP_SENT',
  OTP_SEND_FAILED: 'OTP_SEND_FAILED',
  OTP_VERIFIED: 'OTP_VERIFIED',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  GOOGLE_LOGIN_STARTED: 'GOOGLE_LOGIN_STARTED',
  GOOGLE_LOGIN_SUCCESS: 'GOOGLE_LOGIN_SUCCESS',
  GOOGLE_LOGIN_FAILED: 'GOOGLE_LOGIN_FAILED',
  TOKEN_REFRESHED: 'TOKEN_REFRESHED',
  TOKEN_REFRESH_FAILED: 'TOKEN_REFRESH_FAILED',
  USER_IDENTIFIED: 'USER_IDENTIFIED',
  LOGOUT: 'LOGOUT',

  // Home / profile
  HOME_VIEWED: 'HOME_VIEWED',
  PROFILE_FETCHED: 'PROFILE_FETCHED',
  PROFILE_VIEWED: 'PROFILE_VIEWED',
  PROFILE_UPDATED: 'PROFILE_UPDATED',
  MODULE_CARD_CLICKED: 'MODULE_CARD_CLICKED',
};
